### ISSUE TITLE
it cannot get text node

### ISSUE THREAD

**Issue by plh97** [thiagodp/get-xpath#11]
to get parent node, it work, but to get text node, not work

![image](https://github.com/user-attachments/assets/e130885a-ed9d-4f3f-9ac5-1dbf2ab33c3a)

**Comment by thiagodp** [comment]
Hello @plh97, as a workaround (to solve your problem), try the following:
```js
const firstTextXPath = getXPath( $0.parentNode ) + '/text()[1]'
```

**Comment by thiagodp** [comment]
Support to text nodes added - see [v3.2.0](https://github.com/thiagodp/get-xpath/releases/tag/v3.2.0)
